### ISSUE TITLE
Frontend default asset management

### ISSUE THREAD

**Issue by alexchepura** [spiral-modules/toolkit#13]
We have to come up with some sort of dependencies management for zero configurated frontend.

Some thoughts:

``` html
<require:script module=«spiral.core» href=«fallback path»/>
<require:script href=«compiled.js» includes=«spiral.*,project.*»/>
```

After all we need to have ability to bundle frontend with tools like gulp or webpack.

**Comment by wolfy-j** [comment]
Basically every required resource must declare needed modules and fallback url (optional?).

For example forms might request:

```html
<require:script module="sf.core" href="path-to/sf.js"/>
<require:script module="sf.forms" href="path-to/sf-forms.js"/>
```

After that, if develop compiled multiple js files into one bundle which is connected in a parent layout for example he has to declare included extesions:

```html
<require:script module="sf.core, sf.forms, app.main" href="path-to/compiled.js"/>
```

It will be reasonable to allow star pattern:

```html
<require:script module="sf.*, app.*" href="path-to/compiled.js"/>
```

> Good naming for "module" attribute is required.
